clear;clc;
B=imread('DLRB.jpg');%读取美女图片
C=imread('Cat.jpg');%读取猫图片
%类型转换
B1=fft2(double(B));
C1=fft2(double(C));
%计算幅度和相位谱
B2=abs(B1);
B3=angle(B1);
C2=abs(C1);
C3=angle(C1);
%交换重建复数矩阵,必须保证两张图片维度一致
B4=B2.*cos(C3)+B2.*sin(C3).*i;%美女幅度谱与猫的相位谱结合
C4=C2.*cos(B3)+C2.*sin(B3).*i;%猫幅度谱与美女的相位谱结合
%傅立叶反变换
B5=abs(ifft2(B4));
C5=abs(ifft2(C4));
%输出图像
subplot(2,2,1);
imshow(B);
title('原始美女图像');
subplot(2,2,2);
imshow(C);
title('原始猫图像');
subplot(2,2,3);
imshow(B5);
title('组合后美女图像');
subplot(2,2,2);
imshow(C5);
title('组合后猫图像');